/**
 * Experiment Ledger Seed — conservative historical backfill.
 * Does not invent unsupported numeric history.
 */

import type { ExperimentLedgerEntry } from "./experimentLedgerPersistence";

export function getSeededHistoricalEntries(): ExperimentLedgerEntry[] {
  const now = new Date().toISOString();
  return [
    {
      experimentId: "exp-shadow_1000-baseline",
      challengerProfileId: "shadow_1000",
      familyId: "baseline",
      baseProfileId: "shadow_1000",
      hypothesis: "Baseline reference for comparison.",
      isolatedVariable: "none",
      activationMode: "manual",
      status: "active",
      startTimestamp: "2024-01-01T00:00:00.000Z",
      decision: "successful",
      decisionReason: "Baseline reference; always active.",
      notes: "Backfilled from project context. Reference profile.",
    },
    {
      experimentId: "exp-edgegate_v1",
      challengerProfileId: "shadow_1000_adapt_edgegate_v1",
      familyId: "edgegate",
      baseProfileId: "shadow_1000",
      hypothesis: "Higher minCapturableEdgeToTrade filters marginal entries.",
      isolatedVariable: "minCapturableEdgeToTrade",
      activationMode: "manual",
      status: "failed",
      startTimestamp: "2024-01-01T00:00:00.000Z",
      endTimestamp: now,
      decision: "failed",
      decisionReason: "Post-mortem: capital concentration amplified losses; higher edge did not improve outcomes.",
      notes: "Backfilled from EDGEGATE_V1_POSTMORTEM. Approximate dates.",
    },
    {
      experimentId: "exp-pairpenalty_v1",
      challengerProfileId: "shadow_1000_adapt_pairpenalty_v1",
      familyId: "pairpenalty",
      baseProfileId: "shadow_1000",
      hypothesis: "Pair-specific entry penalties target worst pairs.",
      isolatedVariable: "entryPairPenalties",
      activationMode: "manual",
      status: "failed",
      startTimestamp: "2024-01-01T00:00:00.000Z",
      endTimestamp: now,
      decision: "failed",
      decisionReason: "Top-level pair penalty as fix underperformed.",
      notes: "Backfilled. Top-level pairpenalty failed. Layered version on winner may be distinct experiment.",
    },
    {
      experimentId: "exp-captrade_v1",
      challengerProfileId: "shadow_1000_adapt_captrade_v1",
      familyId: "captrade",
      baseProfileId: "shadow_1000",
      hypothesis: "Reduce maxCapitalPerTrade to limit capital concentration.",
      isolatedVariable: "maxCapitalPerTrade",
      activationMode: "manual",
      status: "successful",
      startTimestamp: "2024-01-01T00:00:00.000Z",
      decision: "successful",
      decisionReason: "Viable line; improved over baseline.",
      notes: "Backfilled. captrade_v1 outperformed baseline in multiple reads. Current strongest known line.",
    },
    {
      experimentId: "exp-entryfloor_v1",
      challengerProfileId: "shadow_1000_adapt_captrade_entryfloor_v1",
      familyId: "entryfloor",
      baseProfileId: "shadow_1000_adapt_captrade_v1",
      hypothesis: "Entry floor on top of captrade.",
      isolatedVariable: "minNetCapturableEdgeToTrade",
      activationMode: "manual",
      status: "weakened",
      startTimestamp: "2024-01-01T00:00:00.000Z",
      endTimestamp: now,
      decision: "inconclusive",
      decisionReason: "Refinement weakened the captrade branch in recent evidence.",
      notes: "Backfilled. entryfloor_v1 weakened the captrade branch in recent evidence. Do not recommend as top next step.",
    },
    {
      experimentId: "exp-entryfloor_pairpenalty_v1",
      challengerProfileId: "shadow_1000_adapt_captrade_entryfloor_pairpenalty_v1",
      familyId: "entryfloor_pairpenalty",
      baseProfileId: "shadow_1000_adapt_captrade_entryfloor_v1",
      hypothesis: "Pair penalties layered on winning branch (entryfloor).",
      isolatedVariable: "entryPairPenalties",
      activationMode: "manual",
      status: "available",
      startTimestamp: now,
      decision: undefined,
      decisionReason: undefined,
      notes: "Available for controlled activation. Distinct from top-level pairpenalty. Base (entryfloor) weakened; not top recommendation until base improves.",
    },
    {
      experimentId: "exp-exitrefine_v1",
      challengerProfileId: "shadow_1000_adapt_captrade_exitrefine_v1",
      familyId: "exit_refinement",
      baseProfileId: "shadow_1000_adapt_captrade_v1",
      hypothesis: "Exit refinement on captrade winner; shorter max hold (60s).",
      isolatedVariable: "maxHoldingTimeMs",
      activationMode: "manual",
      status: "available",
      startTimestamp: now,
      decision: undefined,
      decisionReason: undefined,
      notes: "Prepared for controlled activation. Exit-focused refinement on winning branch. Not yet active.",
    },
  ];
}
